import pandas as pd
import numpy as np


df=pd.read_csv("RBI_Data_2.0.csv")

variable_names={
    "Currency_in_circulation_Total": "Currency in Circulation",
    "Other_deposits_with_RBI": "Other Deposits with RBI",
    "Bankers_deposits_with_RBI": "Bankers' Deposits with RBI",
    "Reserve_Money_(Liabilities/Components)": "Reserve Money",
    "RBIs_Claims_on_Government(net)": "RBI Claims on Government",
    "RBIs_Claims_on_Central_Govt": "RBI Claims on Central Government",
    "RBIs_Claims_on_Banks_and_Commercial_sector": "RBI Claims on Banks & Commercial Sector",
    "RBIs_Claims_on_Banks_(Including NABARD)": "RBI Claims on Banks",
    "RBIs_claims_on_Commercial_sector_(Excluding NABARD)": "RBI Claims on Commercial Sector",
    "Net_foreign_exchange_assets_of_RBI": "Net Foreign Exchange Assets",
    "Govts_currency_liabilities_to_the_public": "Government Currency Liabilities",
    "Net_non_monetary_liabilities_of_RBI": "Net Non-Monetary Liabilities"
}
def cleaned_data():
    df=pd.read_csv("RBI_Data_2.0.csv")
    data=df.copy(deep=True)
    data["Date"]=pd.to_datetime(data["Date"],format="%d-%m-%Y")
    data.set_index("Date",inplace=True)
    complete_range=pd.date_range(start='2001-07-06',end='2020-08-21',freq='W-FRI')
    data=data.reindex(complete_range)
    special_col="RBIs_Claims_on_Central_Govt"
    for i in data.columns:
        if(i==special_col):
            data[i]=data[i].interpolate(method="linear",limit_area="inside")  ## limit_area calculates only those missing value whose surrounding values are knowe
        else:
            data[i]=data[i].interpolate(method="linear")
    return data

cleaned_df=cleaned_data()


def cleaned_data_1(window_size=12, z_threshold=3.0):
    # Start directly with the data generated by your first function
    data = cleaned_df.copy(deep=True)
    
    # Apply rolling outlier detection to every column
    for col in data.columns:
        rolling_mean = data[col].rolling(window=window_size, min_periods=1, center=True).mean()
        rolling_std = data[col].rolling(window=window_size, min_periods=1, center=True).std()
        
        # Prevent division by zero if standard deviation is zero
        rolling_std = rolling_std.replace(0, np.nan).bfill()
        
        # Calculate dynamic rolling Z-scores
        z_scores = (data[col] - rolling_mean) / rolling_std
        
        # Strip out data points exceeding our statistical threshold
        data.loc[z_scores.abs() > z_threshold, col] = np.nan
        
        # Smooth out the missing gaps left by outliers using linear interpolation
        data[col] = data[col].interpolate(method="linear")
        
    return data

cleaned_df_1 = cleaned_data_1()